export const t = {
  about_me: "About Me",
  hello_im: "Hi, I'm Juan Ignacio!",
  hello_subtitle: "Full Stack",
  hello_subtitlePartColor: "Web Developer",
  hello_subtitlePart2: "Based in Argentina, I build fast, scalable web products focused on real results.",
  my_mission: "Studying at UTN",
  my_missionSubtitle: "Currently enrolled in the",
  my_missionSubtitleColor: "University Technician in Programming.",
  my_missionSubtitle2: "",
  my_missionSubtitle3: "",
  my_missionSubtitle4: "",
  my_missionSubtitleColor2: "",
  my_missionSubtitleColor3: "",
  my_missionSubtitleColor4: "Follow my progress ",

  i_am: "I'm a",
  about_meDescColor: "full stack web developer",
  about_meDesc: "focused on the modern ecosystem:",
  about_meDescColor2: "Next.js, Astro and React.",
  about_meDesc2: "I started coding in 2022 and since then I've worked on real projects for clients in the hospitality and tourism industry in Argentina.",

  about_meDesc3: "Before switching to development, I worked in digital communications — which gives me a broader perspective on how technical decisions affect the end user.",
  about_meDescColor4: "",
  about_meDesc4: "",

  about_meDesc5: "I'm currently studying the",
  about_meDescColor5: "University Technician in Programming",
  about_meDesc6: "at UTN.",
  about_meDescColor6: "",
  about_meDesc7: "I wrote my first line of code around",
  about_meDesc8: "and I haven't stopped building since.",

  visit_gitHub: "Visit my GitHub",
  contact_me: "Contact Me",

  my_studies: "My Studies",
  my_studies_subtitle: "My academic background and the projects I've built along the way.",
  my_studies_subtitle2: "",
  download_cv: "Download CV",

  curse_1: "Full Stack Web Development",
  curse_1_desc: "Intensive 6-month course focused on full stack methodologies and SEO fundamentals.",

  curse_2: "UX-UI Design",
  curse_2_desc: "Modern, intuitive interface design focused on user experience.",

  university: "University Technician in Programming",
  university_desc: "Data structures, algorithms and software architecture. In progress since March 2026.",
  university_name: "National Technological University (UTN)",

  university_follow: "Follow my progress →",

  projects_title: "Featured Projects",
  projects_subTitle: "Real work for real clients: websites and tools focused on performance, SEO and solving concrete business problems.",
  projects_client_title: "Client work",
  projects_personal_title: "Products & personal projects",
  projects_personal_subTitle: "What I build on my own: AI products and game systems development.",
  view_code: "Code",
  view_site: "Live site",

  project_ayresCalafate: "Ayres de Calafate | Boutique Hotel",
  project_ayresCalafate_highlight: "Lighthouse 40 → 100",
  project_ayresCalafate_desc: "Official website for a boutique hotel in El Calafate, Patagonia. I owned the whole project: UI design, development and booking engine integration. I built the first version with React + Vite; when the site needed SSR and real SEO, I migrated it to Next.js 15 with the App Router, added internationalization in three languages (ES/EN/PT) with next-intl, and reorganized the code into reusable modules with CSS Modules. Lighthouse performance went from 40 to 100.",

  project_ayresDorados: "Ayres Dorados | Lodge Hotel",
  project_ayresDorados_desc: "Website for a lodge in Sierra Grande, Río Negro (Argentina), which I built from scratch: design, development and booking engine integration. I chose Astro to serve static HTML on first render and used React islands only where interactivity is needed, such as the gallery and carousel. It loads fast on mobile connections, which is where conversion happens in tourism.",

  project_simplicitySystems: "Simplicity Systems | Internal tools",
  project_simplicitySystems_highlight: "In use at Ayres Dorados",
  project_simplicitySystems_desc: "A management system the Ayres Dorados front desk uses every day to enter bookings, track availability and generate vouchers. I kept it separate from the public website: bookings are validated in the form and synced to Google Sheets through Apps Script, and vouchers are generated as PDFs with a live preview using React-PDF, with no server needed.",

  project_briefAI: "aiBrief | AI branding assistant",
  project_briefAI_highlight: "Full stack + AI",
  project_briefAI_desc: "A full stack app that turns a business idea into a complete brand brief: strategy, color palette, typography and user persona generated by an LLM, plus a logo and mockups created with image models (FLUX). It includes a chat to refine sections of the brief and PDF export with Puppeteer. Frontend in Next.js with Tailwind and shadcn/ui; backend in Express with MySQL.",

  project_snow: "Project Snow | FiveM server",
  project_snow_highlight: "16 custom Lua scripts",
  project_snow_desc: "A post-apocalyptic survival roleplay server built on QBCore. I wrote the core systems in Lua: body temperature driven by weather, radiation, zombie infection, illnesses that progress in stages, and synced dynamic events such as meteorite strikes. I also built the official website in Next.js 16, with a Discord bot and automated performance audits using Lighthouse and Playwright.",

  wanna_see_more: "Want to see more?",
  see_all_projects: "See all projects",

  my_skills: "My Skills",
  design: "Design",
  my_projects: "My projects",
  home: "Home",
  available_to_work: "Available to work",
  hero_cta_projects: "See projects",
  connect_title: "Connect",
  connect_subtitle: "Write to me or download my professional info.",
  meta_title: "Juan Ignacio Centeno | Full Stack Web Developer",
  meta_description: "Professional portfolio of Juan Ignacio Centeno, Full Stack Web Developer from Argentina. Discover my web development projects and programming studies.",
}